#!/usr/bin/env bash
# =============================================================================
# Wekan Docker Setup Script
# Tested on Debian 13 (Trixie)
# Installs Docker, Docker Compose plugin, and launches Wekan with persistent
# MongoDB data stored on the host machine.
# =============================================================================

set -euo pipefail

# ─── Colour helpers ───────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*" >&2; exit 1; }

# ─── Configuration (edit these if needed) ─────────────────────────────────────
INSTALL_DIR="${HOME}/wekan"
HOST_PORT="8080"
ROOT_URL="http://localhost:${HOST_PORT}"   # Change to your server IP/domain if remote
MONGO_IMAGE="mongo:6"
WEKAN_IMAGE="ghcr.io/wekan/wekan:latest"

# ─── 1. Check we're running as a normal user (not root) ───────────────────────
if [[ "${EUID}" -eq 0 ]]; then
  error "Do NOT run this script as root. Run as your normal user; sudo will be used where needed."
fi

echo -e "\n${BOLD}╔══════════════════════════════════════╗"
echo -e "║       Wekan Docker Setup Script      ║"
echo -e "╚══════════════════════════════════════╝${RESET}\n"

# ─── 2. Install Docker if not present ─────────────────────────────────────────
if command -v docker &>/dev/null; then
  success "Docker already installed: $(docker --version)"
else
  info "Installing Docker and Docker Compose plugin..."
  sudo apt-get update -qq
  sudo apt-get install -y -qq \
    ca-certificates curl gnupg lsb-release apt-transport-https

  # Add Docker's official GPG key
  sudo install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/debian/gpg \
    | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  sudo chmod a+r /etc/apt/keyrings/docker.gpg

  # Add Docker repo (use bookworm codename; Trixie uses same packages)
  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/debian bookworm stable" \
    | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

  sudo apt-get update -qq
  sudo apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin

  success "Docker installed: $(docker --version)"
fi

# ─── 3. Ensure current user is in the docker group ────────────────────────────
if groups "${USER}" | grep -q docker; then
  success "User '${USER}' is already in the docker group."
else
  info "Adding user '${USER}' to the docker group..."
  sudo usermod -aG docker "${USER}"
  warn "You have been added to the 'docker' group."
  warn "You may need to log out and back in for group changes to take effect."
  warn "This script will continue using 'sudo docker' for the remainder of this run."
  DOCKER_CMD="sudo docker"
fi
DOCKER_CMD="${DOCKER_CMD:-docker}"

# ─── 4. Ensure Docker daemon is running ───────────────────────────────────────
if ! ${DOCKER_CMD} info &>/dev/null; then
  info "Starting Docker daemon..."
  sudo systemctl enable --now docker
fi
success "Docker daemon is running."

# ─── 5. Create directory structure ────────────────────────────────────────────
info "Creating project directory at: ${INSTALL_DIR}"
mkdir -p "${INSTALL_DIR}"/{data/db,data/db-config,data/wekan/files/attachments}
# Wekan runs as UID 999 inside the container — grant it write access
chmod -R 777 "${INSTALL_DIR}/data/wekan"
success "Directory structure created."

# ─── 6. Write docker-compose.yml ──────────────────────────────────────────────
info "Writing docker-compose.yml..."
cat > "${INSTALL_DIR}/docker-compose.yml" <<EOF
# Wekan + MongoDB — generated by wekan-setup.sh
# Data is persisted under ${INSTALL_DIR}/data/ on the host.

services:
  wekan:
    image: ${WEKAN_IMAGE}
    container_name: wekan
    restart: unless-stopped
    ports:
      - "${HOST_PORT}:8080"
    environment:
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=${ROOT_URL}
      - WITH_API=true
      - WRITABLE_PATH=/data
    depends_on:
      - wekandb
    volumes:
      - ./data/wekan:/data          # Wekan uploads / attachments
    networks:
      - wekan-net

  wekandb:
    image: ${MONGO_IMAGE}
    container_name: wekandb
    restart: unless-stopped
    command: mongod --logpath /dev/null
    volumes:
      - ./data/db:/data/db          # MongoDB data files
      - ./data/db-config:/data/configdb
    networks:
      - wekan-net

networks:
  wekan-net:
    driver: bridge
EOF
success "docker-compose.yml written."

# ─── 7. Write a handy management helper script ────────────────────────────────
info "Writing wekan-ctl.sh helper..."
cat > "${INSTALL_DIR}/wekan-ctl.sh" <<'HELPER'
#!/usr/bin/env bash
# Quick management helper for Wekan
cd "$(dirname "$0")"
case "${1:-help}" in
  start)   docker compose up -d ;;
  stop)    docker compose down ;;
  restart) docker compose down && docker compose up -d ;;
  logs)    docker compose logs -f wekan ;;
  status)  docker compose ps ;;
  update)  docker compose pull && docker compose up -d ;;
  backup)
    TS=$(date +%Y%m%d_%H%M%S)
    docker exec wekandb mongodump --archive \
      | gzip > "./data/backup_${TS}.gz"
    echo "Backup saved: ./data/backup_${TS}.gz"
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|logs|status|update|backup}"
    ;;
esac
HELPER
chmod +x "${INSTALL_DIR}/wekan-ctl.sh"
success "wekan-ctl.sh written."

# ─── 8. Pull images and start containers ──────────────────────────────────────
info "Pulling Docker images (this may take a minute)..."
cd "${INSTALL_DIR}"
${DOCKER_CMD} compose pull

info "Starting Wekan..."
${DOCKER_CMD} compose up -d

info "Restarting Wekan to apply volume permissions..."
${DOCKER_CMD} compose restart wekan

# ─── 9. Wait for Wekan to become ready ────────────────────────────────────────
info "Waiting for Wekan to become ready..."
ATTEMPTS=0
MAX=60
until curl -sf "http://localhost:${HOST_PORT}" -o /dev/null 2>/dev/null; do
  ATTEMPTS=$((ATTEMPTS + 1))
  if [[ ${ATTEMPTS} -ge ${MAX} ]]; then
    warn "Wekan did not respond within ${MAX} seconds."
    warn "It may still be starting. Check logs with: ${INSTALL_DIR}/wekan-ctl.sh logs"
    break
  fi
  sleep 2
done
[[ ${ATTEMPTS} -lt ${MAX} ]] && success "Wekan is up and responding."

# ─── 10. Summary ──────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}╔══════════════════════════════════════════════╗"
echo -e "║             Setup Complete! 🎉              ║"
echo -e "╚══════════════════════════════════════════════╝${RESET}"
echo ""
echo -e "  ${BOLD}Wekan URL:${RESET}       http://localhost:${HOST_PORT}"
echo -e "  ${BOLD}Install dir:${RESET}     ${INSTALL_DIR}"
echo ""
echo -e "  ${BOLD}Persistent data on host:${RESET}"
echo -e "    MongoDB data   → ${INSTALL_DIR}/data/db"
echo -e "    MongoDB config → ${INSTALL_DIR}/data/db-config"
echo -e "    Wekan uploads  → ${INSTALL_DIR}/data/wekan"
echo ""
echo -e "  ${BOLD}Management commands:${RESET}"
echo -e "    ${INSTALL_DIR}/wekan-ctl.sh start"
echo -e "    ${INSTALL_DIR}/wekan-ctl.sh stop"
echo -e "    ${INSTALL_DIR}/wekan-ctl.sh logs"
echo -e "    ${INSTALL_DIR}/wekan-ctl.sh backup"
echo -e "    ${INSTALL_DIR}/wekan-ctl.sh update"
echo ""
if groups "${USER}" | grep -qv docker 2>/dev/null; then
  echo -e "  ${YELLOW}${BOLD}Remember:${RESET} Log out and back in so your docker group membership takes effect."
  echo ""
fi
